### ISSUE TITLE
Probably something to do with exception objects

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mflog#2]
When logger.exception is called with an exception objects rather than a string, the function fails.
See https://github.com/metwork-framework/mfdata/issues/56 (corrected by conversion to str before call to logger.exception)

**Comment by thefab** [comment]
We have:

- [ ] to update mflog in mfext
- [ ] to revert 945fca25c50545dde78a2c620b2252157305f08c in mfdata
